import { createLogger } from '../../core/logger.js';
import { recordingManager, RecordedStep } from '../../session/recording-manager.js';

const logger = createLogger('CodegenHandler');

export interface StartRecordingParams {
  sessionId: string;
}

export interface StopRecordingParams {
  sessionId: string;
}

export interface ExportRecordingParams {
  sessionId: string;
  testName?: string;
}

export class CodegenHandler {
  startRecording(params: StartRecordingParams) {
    const { sessionId } = params;
    recordingManager.start(sessionId);

    logger.info({ sessionId }, 'Codegen recording started');

    return {
      success: true,
      sessionId,
    };
  }

  stopRecording(params: StopRecordingParams) {
    const { sessionId } = params;
    const steps = recordingManager.stop(sessionId);

    logger.info({ sessionId, steps: steps.length }, 'Codegen recording stopped');

    return {
      success: true,
      sessionId,
      steps,
    };
  }

  exportRecordingAsTest(params: ExportRecordingParams) {
    const { sessionId, testName } = params;
    const steps = recordingManager.getSteps(sessionId);
    const resolvedTestName = testName || `recorded flow for ${sessionId}`;

    const testCode = this.generateTestCode(steps, resolvedTestName);

    logger.info({ sessionId, steps: steps.length }, 'Generated test code from recording');

    return {
      success: true,
      sessionId,
      testName: resolvedTestName,
      testCode,
    };
  }

  private generateTestCode(steps: RecordedStep[], testName: string): string {
    const lines: string[] = [];

    lines.push(`import { test } from '@playwright/test';`);
    lines.push('');
    lines.push(`test(${JSON.stringify(testName)}, async ({ page }) => {`);
    lines.push(`  // Generated by electron-mcp-server codegen`);

    for (const step of steps) {
      switch (step.type) {
        case 'navigate':
          lines.push(`  await page.goto(${JSON.stringify(step.url)});`);
          break;
        case 'click':
          lines.push(`  await page.click(${JSON.stringify(step.selector)});`);
          break;
        case 'fill':
          lines.push(
            `  await page.fill(${JSON.stringify(step.selector)}, ${JSON.stringify(step.value)});`
          );
          break;
        case 'select':
          lines.push(
            `  await page.selectOption(${JSON.stringify(step.selector)}, ${JSON.stringify(
              step.value
            )});`
          );
          break;
        case 'wait_for_selector': {
          const options: Record<string, unknown> = {};
          if (step.state) {
            options.state = step.state;
          }
          if (step.timeout) {
            options.timeout = step.timeout;
          }
          const optionsLiteral =
            Object.keys(options).length > 0 ? `, ${JSON.stringify(options)}` : '';
          lines.push(
            `  await page.waitForSelector(${JSON.stringify(step.selector)}${optionsLiteral});`
          );
          break;
        }
        case 'execute':
          lines.push(`  await page.evaluate(${JSON.stringify(step.script)});`);
          break;
        case 'get_page_info':
          lines.push('  // get_page_info step (page URL and title already implicit)');
          break;
        default:
          lines.push(`  // Unsupported step type: ${(step as any).type}`);
      }
    }

    lines.push('});');

    return lines.join('\n');
  }
}

